# Generated by Django 2.2.9 on 2020-01-14 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileset',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilesets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileset',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='basemaps',
            field=models.ManyToManyField(blank=True, to='profiles.Basemap'),
        ),
        migrations.AddField(
            model_name='profile',
            name='otherfiles',
            field=models.ManyToManyField(blank=True, to='profiles.Otherfiles'),
        ),
        migrations.AddField(
            model_name='profile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Project'),
        ),
        migrations.AddField(
            model_name='profile',
            name='spatialitedbs',
            field=models.ManyToManyField(blank=True, to='profiles.Spatialitedbs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Tag'),
        ),
    ]
