# Generated by Django 2.2.9 on 2020-01-14 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='название подразделения')),
                ('description', models.CharField(max_length=300, verbose_name='краткое описание')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='название проекта')),
                ('description', models.CharField(max_length=30, verbose_name='краткое описание')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Subdivision')),
            ],
        ),
    ]
