# Generated by Django 2.2.9 on 2020-01-15 12:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_subdivision_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='subdivision',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AddField(
            model_name='subdivision',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 12, 58, 21, 576543), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Subdivision', verbose_name='подразделение'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='участники'),
        ),
    ]
