# Generated by Django 3.0.1 on 2019-12-24 06:48

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, default='', max_length=100)),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('url', models.FileField(upload_to='basemaps/')),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ('path', '-modifieddate'),
            },
        ),
        migrations.CreateModel(
            name='Otherfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, default='', max_length=100)),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('url', models.FileField(upload_to='otherfiles/')),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'ordering': ('path', '-modifieddate'),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(default='#FBC02D', max_length=30)),
                ('active', models.BooleanField(default=False)),
                ('sdcardPath', models.CharField(default='MAINSTORAGE', max_length=100)),
                ('mapView', models.CharField(default='52.02025604248047,-115.70208740234375,10.0', max_length=100)),
                ('basemaps', models.ManyToManyField(blank=True, to='profiles.Basemap')),
                ('otherfiles', models.ManyToManyField(blank=True, to='profiles.Otherfiles')),
            ],
            options={
                'ordering': ('modifieddate', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, default='', max_length=100)),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('url', models.FileField(upload_to='projects/')),
                ('uploadurl', models.URLField(blank=True)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('path', '-modifieddate'),
            },
        ),
        migrations.CreateModel(
            name='Spatialitedbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, default='', max_length=100)),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('url', models.FileField(upload_to='spatialitedbs/')),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('uploadurl', models.URLField(blank=True)),
                ('visible', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
            ],
            options={
                'ordering': ('path', '-modifieddate'),
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to=profiles.models.userproject_directory_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('owner', '-modifieddate'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, default='', max_length=100)),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('url', models.FileField(upload_to=profiles.models.tag_directory_path)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('path', '-modifieddate'),
            },
        ),
        migrations.CreateModel(
            name='ProfileSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatVersion', models.FloatField(default=1.1)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilesets', to=settings.AUTH_USER_MODEL)),
                ('profiles', models.ManyToManyField(blank=True, to='profiles.Profile')),
            ],
            options={
                'ordering': ('owner',),
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Project'),
        ),
        migrations.AddField(
            model_name='profile',
            name='spatialitedbs',
            field=models.ManyToManyField(blank=True, to='profiles.Spatialitedbs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Tag'),
        ),
    ]
