# Generated by Django 3.0.1 on 2019-12-24 05:10

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import gp_projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linestring', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('timestamp_start', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp at start')),
                ('timestamp_end', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp at end')),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text note')),
                ('lengthm', models.FloatField(blank=True, null=True, verbose_name='Track length in metres')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('lat', models.FloatField(verbose_name='Latitude (WGS84)')),
                ('lon', models.FloatField(verbose_name='Longitude (WGS84)')),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Note type')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text note')),
                ('form', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Form element')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('lat', models.FloatField(verbose_name='Latitude (WGS84)')),
                ('lon', models.FloatField(verbose_name='Longitude (WGS84)')),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=gp_projects.models.userdata_directory_path)),
                ('thumbnail', models.ImageField(upload_to=gp_projects.models.userdata_directory_path)),
                ('azimuth', models.FloatField(blank=True, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gp_projects.Note')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
