# Generated by Django 2.2.9 on 2020-01-14 06:42

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import geopaparazzi.gp_projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('lat', models.FloatField(verbose_name='Latitude (WGS84)')),
                ('lon', models.FloatField(verbose_name='Longitude (WGS84)')),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=geopaparazzi.gp_projects.models.userdata_directory_path)),
                ('thumbnail', models.ImageField(upload_to=geopaparazzi.gp_projects.models.userdata_directory_path)),
                ('azimuth', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('lat', models.FloatField(verbose_name='Latitude (WGS84)')),
                ('lon', models.FloatField(verbose_name='Longitude (WGS84)')),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Note type')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text note')),
                ('form', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Form element')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linestring', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('timestamp_start', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp at start')),
                ('timestamp_end', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp at end')),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text note')),
                ('lengthm', models.FloatField(blank=True, null=True, verbose_name='Track length in metres')),
            ],
        ),
    ]
